version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: auto_school
      MYSQL_USER: auto_school_user
      MYSQL_PASSWORD: auto_school_password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - auto_school_network

networks:
  auto_school_network:
